name: xcorr
channels:
  - conda-forge
  - intel
  - defaults
dependencies:
  - python=3.9
  - numpy
  - scipy
  - matplotlib
  - pandas>=1.1.2
  - seaborn
  - obspy>=1.2.0
  - basemap
  - pyfftw
  - h5py
  - h5netcdf
  - netcdf4
  - xarray>=0.16.0
  - cartopy
  - pyproj
  - pytables
  - dask
  - distributed!=2021.03.0
  - bottleneck
  - python-graphviz
  - bokeh>=2.0
  - greenlet!=0.4.17
  - humanfriendly
  - tabulate
  - dateparser
  - notebook
  - ipython
  - jupyter
  - flake8
  - scikit-learn
  - scikit-image
  - pytables
  - python-slugify
  - pip
  - pip:
    - python-crontab
