name: xcorr
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - numpy
  - scipy
  - numba
  - obspy>=1.2.0
  - pyfftw
  - h5py
  - h5netcdf
  - netcdf4
  - gdal
  - pandas=1.0.5
  - xarray
  - dask
  - distributed
  - mpi4py
  - dask-mpi
  - bottleneck
  - matplotlib
  - nc-time-axis
  - pyproj
  - basemap
  - cartopy
  - humanfriendly
  - tabulate
  - dateparser
  - python-graphviz
  - bokeh=2.0
  - seaborn
  - flake8
  - notebook
  - ipython
  - jupyter
  - python-slugify
  - pip
  - pip:
    - python-crontab
