name: xcorr
channels:
  - conda-forge
  - intel
  - defaults
dependencies:
  - python=3.8
  - numpy
  - scipy
  - matplotlib
  - pandas>=1.1.2
  - obspy>=1.2.0
  - basemap
  - pyfftw>=0.12.0
  - h5py
  - h5netcdf
  - netcdf4
  - xarray>=0.16.0
  - cartopy
  - dask
  - distributed
  - python-graphviz
  - bokeh=2.0
  - pyproj
  - humanfriendly
  - tabulate
  - dateparser
  - notebook
  - ipython
  - jupyter
  - flake8
  - scikit-learn
  - python-slugify
  - pip
  - pip:
    - python-crontab
